# Jekyll
#theme: linkhub-jekyll-theme
remote_theme: digitalmalayali/linkhub-jekyll-theme

# Site Configuration
name: francesco  # Name of your website
tagline: Links  # Set your preferred page title
description: just mix life-long passion for everything IT, add genuine curiosity and season it with love for facing challenges and finding a way around them.  # Also used as a meta description
favicon:
  path: assets/avatar.jpeg # Path / URL to the favicon of your website (e.g., 'assets/images/favicon.png')
  type: jpeg # File format of image. Change according to your image. Supported types: https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Image_types
logo: assets/avatar.jpeg # Path / URL to the logo (e.g., 'assets/images/logo.png')
url: https://fravaccaro.github.io # URL of your website
locale: en_GB # The value specifies the locale in which these tags are marked up. It follows the format `language_TERRITORY`.
ga4: # Google Analytics 4 measurement ID, for e.g. G-XXXXXXX (optional). Remove it if it’s not needed.
image:
  path: assets/avatar.jpeg # Used for SEO (og:image, twitter:image)
  type: jpeg # File format of image.
  height: 100 # Pixels
  width: 100
  alt: avatar

# Verified Badge Configuration
badge:
  enable: false # Set to 'true' or 'false' to enable / disable the badge
  icon: ri:verified-badge-fill  # Enter the icon name for the badge from Iconify Design (https://icon-sets.iconify.design/)
  color: '#dfb221'  # Define the color of the badge
 
# Defaults
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"    

# Exclude
exclude: [README.md, Gemfile.lock, .jekyll-cache/, .github/, CHANGELOG.md, Gemfile, LICENSE.txt, funding.yml, linkhub-jekyll-theme.gemspec]
